config/routes.rb
MusicApp::Application.routes.draw do

  root to: 'bands#index'

  resources :users, only: [:new, :create] do
    member do
      get 'activate'
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :bands

  resources :albums

  resources :tracks do
    resources :notes, except: [:destroy]
  end

  resources :notes, only: [:destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :band_id, :album_type

  belongs_to :band,
  :foreign_key => :band_id,
  :primary_key => :id,
  :class_name => "Band"

  has_many :tracks,
  :foreign_key => :album_id,
  :primary_key => :id,
  :class_name => "Track",
  :dependent => :destroy

end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many :albums,
  :foreign_key => :band_id,
  :primary_key => :id,
  :class_name => "Album",
  :dependent => :destroy

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :user_id, :track_id, :text

  belongs_to :user,
  :foreign_key => :user_id,
  :primary_key => :id,
  :class_name => "User"

  belongs_to :track,
  :foreign_key => :track_id,
  :primary_key => :id,
  :class_name => "Track"

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :album_id, :track_type, :lyrics

  belongs_to :album,
  :foreign_key => :album_id,
  :primary_key => :id,
  :class_name => "Album"

  has_many :notes,
  :foreign_key => :track_id,
  :primary_key => :id,
  :class_name => "Note",
  :dependent => :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token, :activation_token, :activated


  before_validation(:ensure_session_token, on: :create)
  before_validation(:ensure_activation_token, on: :create)

  validates :email, :session_token, presence: true
  validates :email, uniqueness: true

  has_many :notes,
  :foreign_key => :user_id,
  :primary_key => :id,
  :class_name => "Note",
  :dependent => :destroy

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_activation_token
    self.activation_token = self.class.generate_session_token
  end

  def password=(secret)
      write_attribute(:password_digest, BCrypt::Password.create(secret))
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def activate!
    self.activated = true
    self.save
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new

    render :new
  end

  def create
    @album = Album.new(params[:album])

    if @album.save
      redirect_to albums_url
    else
      render @album.errors.full_messages, status: :unproccessable_entity
    end
  end

  def edit
    #render :edit ?
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(params[:album])
      redirect_to album_url
    else
      render @album.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])

    @album.destroy

    redirect_to bands_url
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new

    render :new
  end

  def create
    @band = Band.new(params[:band])

    if @band.save
      redirect_to bands_url
    else
      render @band.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    #render :edit ?
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])

    if @band.update_attributes(params[:band])
      redirect_to bands_url
    else
      render @band.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @band = Band.find(params[:id])

    @band.destroy

    redirect_to bands_url
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new

    render partial: 'note'
  end

  def create
    @note = Note.new(params[:note])

    if @note.save
      redirect_to track_url(@note.track_id)
    else
      render @note.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @note = Note.find(params[:id])

    @note.destroy

    redirect_to track_url(@note.track_id)
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update_attributes(params[:note])
      redirect_to track_url
    else
      render @note.errors.full_messages, status: :unprocessable_entity
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user.nil?
      flash[:errors] = "NO!!!!!!!"
      redirect_to new_session_url
    elsif (@user.activated == false)
      flash[:errors] = "ACTIVATE!!!!"
      redirect_to new_session_url
    else
      @user.reset_session_token!

      session[:session_token] = @user.session_token

      redirect_to bands_url
    end
  end

  def destroy
    session_token = session[:session_token]
    @user = User.find_by_session_token(session_token)

    session[:session_token] = nil
    @user.reset_session_token!

    redirect_to bands_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def new
    @track = Track.new

    render :new
  end

  def create
    @track = Track.new(params[:track])

    if @track.save
      redirect_to albums_url
    else
      render @track.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    #render :edit ?
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])

    if @track.update_attributes(params[:track])
      redirect_to albums_url
    else
      render @track.errors.full_messages, status: :unprocessable_entity
    end
  end

  def destroy
    @track = Track.find(params[:id])

    @track.destroy

    redirect_to albums_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      msg = UserMailer.welcome_email(@user)
      msg.deliver!
      # log_in_user!
      redirect_to bands_url
    else
      render @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  # def activate
  #   @user = User.find(params[:id])
  #
  #   if @user.activation_token == @query
  #     @user.activate!
  #     redirect_to bands_url
  #   else
  #     flash[:errors] = "Not activated!"
  #   end
  # end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    return true unless current_user.nil?
  end

  def log_in_user!
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    session[:session_token] = @user.session_token

    redirect_to bands_url
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<h1>Album Form dude!</h1>
<form action="/albums/<%= @album.id %>" method="post">
  <input type="hidden" name="_method" value=<%= 'PUT' if @album.persisted? %>>

  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <table>

<!-- band drop down menu -->
    <tr align="left"><th><label for="album_title">Name</label>

    <td><input name ="album[title]" id="album_title" type="text" value="<%= @album.title %>">

      <tr align="left"><th><label for="album_band">Band</label>
      <td><select name="album[band_id]">
        <% Band.all.each do |band| %>

          <option value="<%= band.id %>" <%= "selected" if (band.id == params[:id]) %> >
            <%= band.name %>
          </option>

        <% end %>
<!-- album type -->
      <tr align="left"><th><label>Type:</label>
      <td><input name="album[album_type]" id="album_type_studio" type="radio" value="Studio" <%= "checked" if @album.album_type == "Studio" %>>
      <label for="album_type_studio">Studio</label>
      <input name="album[album_type]" id="album_type_live" type="radio" value="Live" <%= "checked" if @album.album_type == "Live" %>>
      <label for="album_type_live">Live</label>

  </table>

  <input type="submit" value="<%= @album.persisted? ? 'Edit this album!' : 'Add this album!' %>" >

</form>

<br>

<a href="/bands">Back to the bands page!</a>

app/views/albums/edit.html.erb
<%= render partial: 'form' %>

app/views/albums/index.html.erb
<h1>All Albums</h1>
<ul>
  <% @albums.each do |album| %>
    <li><a href="/albums/<%=album.id%>"><%= album.title %> (<%= album.band.name %>)</a></li>
    <br>
  <% end %>
</ul>

<a href="/bands/<%= Band.find(@albums.first.band_id).id %>/albums/new">Add an album!</a>

<br><br>

<a href="/bands/">Back to main page</a>

app/views/albums/new.html.erb
<%= render partial: 'form' %>

app/views/albums/show.html.erb
<h1><%= @album.band.name %></h1>
<h2><%= @album.title %></h2>


<h3>Track List</h3>

<ul>
  <% @album.tracks.each do |track| %>
    <li><a href="/tracks/<%= track.id %>"><%= track.title %></a></li>
    <br>
  <% end %>

</ul>

<a href="/tracks/new">Add a track!</a>

<br><br>

<%= button_to "Delete Album", @album, :method => :delete %>

<br><br>

<a href="/bands/<%=@album.band.id%>">Back to band</a>

app/views/bands/_form.html.erb
<h1>Band Form yo!</h1>
<form action="/bands/<%= @band.id %>" method="post">
  <input type="hidden" name="_method" value=<%= 'PUT' if @band.persisted? %>>

  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

  <table>

    <tr align="left"><th><label for="band_name">Band Name</label>
    <td><input name ="band[name]" id="band_name" type="text" value="<%= @band.name %>">

  </table>

  <input type="submit" value="<%= @band.persisted? ? 'Edit this band!' : 'Add this band!' %>" >

</form>

<br>

<a href="/bands/">Back to the main page!</a>

app/views/bands/edit.html.erb
<%= render partial: 'form' %>

app/views/bands/index.html.erb
<h1>Band List</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="/bands/<%=band.id%>"><%= band.name %></a></li>
    <br>
  <% end %>
</ul>

<a href="/bands/new">Add a band!</a>

app/views/bands/new.html.erb
<%= render partial: 'form' %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<h3>Albums</h3>
<ul>
  <% @band.albums.each do |album| %>
    <li><a href="/albums/<%= album.id %>"><%= album.title %></a></li>
    <br>
  <% end %>
</ul>

<a href="/albums/new">Add an album!</a>

<br><br>

<%= button_to "Delete Band", @band, :method => :delete %>

<br><br>

<a href="/bands/">Back to main page</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>

      Logged in as: <%= current_user.email %>
      <%= button_to "Logout", session_url(current_user), :method => :delete %>


  <% else %>
    <%= button_to "Login", new_session_url, :method => :get %>
    <%= button_to "Sign Up", new_user_url, :method => :get %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/notes/_note.html.erb
<h1>It's note time!</h1>

<form action="/tracks/<%= params[:track_id] %>/notes/<%= @note.id %>" method="post">
  <input type="hidden" name="_method" value=<%= 'PUT' if @note.persisted? %>>

  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

    <input name="note[user_id]" type="hidden" value="<%=current_user.id%>">

    <input name="note[track_id]" type="hidden" value="<%=params[:track_id]%>">

    <table>
<!-- note -->

      <tr align="left"><th><label for="note_text">Note</label>

      <td><textarea rows="4" cols="50" input name="note[text]" id="note_text" value="<%= @note.text %>"></textarea>

</table>

  <input type="submit" value="<%= @note.persisted? ? 'Edit this note!' : 'Add this note!' %>" >

</form>

<br>

<a href="/albums">Back to the albums page!</a>
<br><br>
<a href="/bands">Back to the bands page!</a>

app/views/tracks/_form.html.erb
<h1>Track Form man!</h1>
<form action="/tracks/<%= @track.id %>" method="post">
  <input type="hidden" name="_method" value=<%= 'PUT' if @track.persisted? %>>

  <input
    name="authenticity_token"
    type="hidden"
    value="<%= form_authenticity_token %>">

    <table>
<!-- album drop down menu -->
    <tr align="left"><th><label for="track_title">Name</label>

    <td><input name ="track[title]" id="track_title" type="text" value="<%= @track.title %>">

      <br>

      <tr align="left"><th><label for="track_album_id">Album</label>
      <td><select name="track[album_id]">
        <% Album.all.each do |album| %>

          <option value="<%= album.id %>">
            <%= album.title %>
          </option>

        <% end %>
      </select>

<!-- track type -->
      <tr align="left"><th><label>Type:</label>
      <td><input name="track[track_type]" id="track_type_regular" type="radio" value="Regular" <%= "checked" if @track.track_type == "Regular" %>>
      <label for="track_type_regular">Regular</label>
      <input name="track[track_type]" id="track_type_bonus" type="radio" value="Bonus" <%= "checked" if @track.track_type == "Bonus" %>>
      <label for="track_type_bonus">Bonus</label>


<!-- track lyrics -->

      <tr align="left"><th><label for="track_title">Lyrics</label>

      <td><textarea rows="4" cols="50" input name ="track[lyrics]" id="track_lyrics" value="<%= @track.lyrics %>">
      </textarea>



</table>

  <input type="submit" value="<%= @track.persisted? ? 'Edit this track!' : 'Add this track!' %>" >

</form>

<br>

<a href="/albums">Back to the albums page!</a>
<br><br>
<a href="/bands">Back to the bands page!</a>

app/views/tracks/edit.html.erb
<%= render partial: 'form' %>

app/views/tracks/new.html.erb
<%= render partial: 'form' %>

app/views/tracks/show.html.erb
<h1><%= @track.album.band.name %></h1>
<h2><%= @track.album.title %></h2>
<h3><%= @track.title %></h3>

<b>Track Type:</b> <%= @track.track_type %>

<br><br>

<b>Lyrics:</b> <%= @track.lyrics %>

<br><br>

<b>Notes:</b><br>
<% Note.all.each do |note| %>
  <% if note.track_id == @track.id %>

    <%= note.text %>
    <% if note.user_id == current_user.id %>
    <%= button_to "Delete Note", note, :method => :delete %>
    <% end %>
    <br>

  <% end %>
<% end %>


<a href="/tracks/<%=@track.id%>/notes/new">Add a note!</a>

<br><br>

<%= button_to "Delete Track", @track, :method => :delete %>

<br>

<a href="/albums/<%=@track.album.id%>">Back to album</a>

app/views/users/activate.html.erb
<% current_user = User.find(params[:id]) %>
<% if current_user.activation_token = params[:activation_token] %>
<% current_user.activate! %>
<%= "Account activated!" %>
<% else %>
<%= "Check your email again" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="post">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_email">Enter your email</label>
  <input
     id="user_email"
     name="user[email]"
     type="text">
  <br>

  <label for="user_password">Enter a Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="Submit">
</form>
<br>
<a href="/bands">Back to bands</a>